---
title: "Practical Machine Learning Course Project"
author: "Derek Bryant"
date: "February 26, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r dependances, include=FALSE}
#Libraries and set seed--------------------------------------------
library("sqldf")
library("caret")
set.seed(102369)
library(tidyverse) 
library(rpart)

#Setup the parallel processing stuff-----------------------------
library(parallel)
library(doParallel)
cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
registerDoParallel(cluster)
```
## Introduction

The basic goal of the project was to predit the manner in which the exercise was
done. Provided was a dataset with 20 cases and a larger dataset from which 
models were built. 

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
